### ISSUE TITLE
You're selecting same elements twice (userPointEl and cpuPointEl)

### ISSUE THREAD

**Issue by Suhail-007** [Johanh0/Rock-Paper-Scissor_Game#3]
https://github.com/Johanh0/Rock-Paper-Scissor_Game/blob/6564280217f255e189290c43333713f3a3afd165/src/js/app.js#L32

**Comment by Johanh0** [comment]
`userPointsElement` and `cpuPointElement` has different ID's, these is for control the different points from the user and the cpu

`const userPointsElement = document.querySelector(`#userPoint`);`
`const cpuPointElement = document.querySelector(`#cpuPoint`);`

is this what are you saying?

If it's not, please explain me, I'll be happy to know what are you seeing that I'm not!

Thank you :)

**Comment by Suhail-007** [comment]
On line 13 and 14 you have the same elements selected with slightly different names

**Comment by Johanh0** [comment]
I see it now! Thank you so much, I'll fix it right now
